"""event_checkins cpf & birth_date

Revision ID: 9b024bd64c71
Revises: 36d1369e84c4
Create Date: 2025-10-22 13:34:59.445448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b024bd64c71'
down_revision = '36d1369e84c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('birth_date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_checkins')),
    sa.UniqueConstraint('event_date', 'cpf', name='uq_event_date_cpf')
    )
    with op.batch_alter_table('event_checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_checkins_event_checkins_cpf'), ['cpf'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_checkins_event_checkins_event_date'), ['event_date'], unique=False)

    op.drop_table('_alembic_tmp_matriculas')
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=11),
               nullable=False)
        batch_op.alter_column('birth_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_matriculas_code'))
        batch_op.drop_index(batch_op.f('ix_matriculas_cpf'))
        batch_op.create_index(batch_op.f('ix_matriculas_matriculas_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_matriculas_matriculas_cpf'), ['cpf'], unique=True)

    with op.batch_alter_table('presencas', schema=None) as batch_op:
        batch_op.alter_column('date_key',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_presencas_date_key'))
        batch_op.drop_index(batch_op.f('ix_presencas_matricula_id'))
        batch_op.create_index(batch_op.f('ix_presencas_presencas_date_key'), ['date_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_presencas_presencas_matricula_id'), ['matricula_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presencas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presencas_presencas_matricula_id'))
        batch_op.drop_index(batch_op.f('ix_presencas_presencas_date_key'))
        batch_op.create_index(batch_op.f('ix_presencas_matricula_id'), ['matricula_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presencas_date_key'), ['date_key'], unique=False)
        batch_op.alter_column('date_key',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matriculas_matriculas_cpf'))
        batch_op.drop_index(batch_op.f('ix_matriculas_matriculas_code'))
        batch_op.create_index(batch_op.f('ix_matriculas_cpf'), ['cpf'], unique=False)
        batch_op.create_index(batch_op.f('ix_matriculas_code'), ['code'], unique=1)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=16),
               nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=32),
               nullable=True)

    op.create_table('_alembic_tmp_matriculas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=16), nullable=False),
    sa.Column('holder_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('cpf', sa.VARCHAR(length=14), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf', name=op.f('uq_matriculas_cpf'))
    )
    with op.batch_alter_table('event_checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_checkins_event_checkins_event_date'))
        batch_op.drop_index(batch_op.f('ix_event_checkins_event_checkins_cpf'))

    op.drop_table('event_checkins')
    # ### end Alembic commands ###
