"""initial

Revision ID: e5314f15f09b
Revises: 9b024bd64c71
Create Date: 2025-10-22 13:58:31.385980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5314f15f09b'
down_revision = '9b024bd64c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_matriculas')
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=11),
               nullable=False)
        batch_op.alter_column('birth_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_matriculas_code'))
        batch_op.drop_index(batch_op.f('ix_matriculas_cpf'))
        batch_op.create_index(batch_op.f('ix_matriculas_matriculas_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_matriculas_matriculas_cpf'), ['cpf'], unique=True)

    with op.batch_alter_table('presencas', schema=None) as batch_op:
        batch_op.alter_column('date_key',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_presencas_date_key'))
        batch_op.drop_index(batch_op.f('ix_presencas_matricula_id'))
        batch_op.create_index(batch_op.f('ix_presencas_presencas_date_key'), ['date_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_presencas_presencas_matricula_id'), ['matricula_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presencas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presencas_presencas_matricula_id'))
        batch_op.drop_index(batch_op.f('ix_presencas_presencas_date_key'))
        batch_op.create_index(batch_op.f('ix_presencas_matricula_id'), ['matricula_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presencas_date_key'), ['date_key'], unique=False)
        batch_op.alter_column('date_key',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matriculas_matriculas_cpf'))
        batch_op.drop_index(batch_op.f('ix_matriculas_matriculas_code'))
        batch_op.create_index(batch_op.f('ix_matriculas_cpf'), ['cpf'], unique=False)
        batch_op.create_index(batch_op.f('ix_matriculas_code'), ['code'], unique=1)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=16),
               nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=32),
               nullable=True)

    op.create_table('_alembic_tmp_matriculas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=16), nullable=False),
    sa.Column('holder_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=11), nullable=False),
    sa.Column('birth_date', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
