"""init_pg

Revision ID: e5e8a142664e
Revises: 
Create Date: 2025-10-23 18:31:04.493456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e8a142664e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('birth_date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_checkins')),
    sa.UniqueConstraint('event_date', 'cpf', name='uq_event_date_cpf')
    )
    with op.batch_alter_table('event_checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_checkins_event_checkins_cpf'), ['cpf'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_checkins_event_checkins_event_date'), ['event_date'], unique=False)

    op.create_table('matriculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('holder_name', sa.String(length=120), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matriculas'))
    )
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matriculas_matriculas_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_matriculas_matriculas_cpf'), ['cpf'], unique=False)

    op.create_table('presencas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula_id', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], name='fk_presencas_matricula_id_matriculas'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_presencas')),
    sa.UniqueConstraint('matricula_id', 'date_key', name='uq_presenca_por_dia')
    )
    with op.batch_alter_table('presencas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presencas_presencas_date_key'), ['date_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_presencas_presencas_matricula_id'), ['matricula_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presencas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presencas_presencas_matricula_id'))
        batch_op.drop_index(batch_op.f('ix_presencas_presencas_date_key'))

    op.drop_table('presencas')
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matriculas_matriculas_cpf'))
        batch_op.drop_index(batch_op.f('ix_matriculas_matriculas_code'))

    op.drop_table('matriculas')
    with op.batch_alter_table('event_checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_checkins_event_checkins_event_date'))
        batch_op.drop_index(batch_op.f('ix_event_checkins_event_checkins_cpf'))

    op.drop_table('event_checkins')
    # ### end Alembic commands ###
